import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prosesmt - Analise COVID-19",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${montserrat.className} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <Header />
        <main className="w-full flex-1 flex justify-center items-center py-10 md:py-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
